---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
```
```{r}
require(tidyverse)
```

```{r}
movies <- read_csv ("movies.csv")
```





```{r}
movies_selected <- movies %>% 
  select(title,runtime,budget,vote_average)
```

```{r}
movies_selected
```

```{r}
movies_selected <- movies %>% 
  select(title,runtime,budget,)
```

```{r}
movies_selected
```

```{r}
movies_selected %>% 
  filter(is.na(budget))
```

```{r}
movies_selected %>% 
  filter(is.na(runtime))
```
```{r}
movies_selected %>% 
  filter(is.na(title))
```

```{r}
movies_selected %>% 
  summarise(na_runtime = sum(is.na(runtime)), 
            na_title = sum(is.na(title)),
            na_budget = sum(is.na(budget)))
```

```{r}
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime = 0))
```

```{r}
movies_runtime <- movies_selected %>% 
  
  mutate(runtime = na_if(runtime, 0))

movies_runtime %>% 
  summarise(count = sum(is.na(runtime)))
```


```{r}
movies_runtime
```

```{r}
movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = TRUE)))
movies_imputed %>% 
  summarise(count = sum(is.na(runtime)))
         

```

